import Foundation

public struct PrivacyPolicy: Equatable, Sendable {
  public var ignoredPasteboardTypes: Set<String>
  public var ignoredTransientTypes: Set<String>
  public var ignoredAppBundleIds: Set<String>
  public var recordsUniversalClipboard: Bool

  public init(
    ignoredPasteboardTypes: Set<String>,
    ignoredTransientTypes: Set<String>,
    ignoredAppBundleIds: Set<String>,
    recordsUniversalClipboard: Bool
  ) {
    self.ignoredPasteboardTypes = ignoredPasteboardTypes
    self.ignoredTransientTypes = ignoredTransientTypes
    self.ignoredAppBundleIds = ignoredAppBundleIds
    self.recordsUniversalClipboard = recordsUniversalClipboard
  }

  public static let standard = PrivacyPolicy(
    ignoredPasteboardTypes: [
      "org.nspasteboard.ConcealedType",
      "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType",
      "com.agilebits.onepassword",
      "BUA8C4S2C.com.1password"
    ],
    ignoredTransientTypes: [
      "org.chromium.web-custom-data"
    ],
    ignoredAppBundleIds: [],
    recordsUniversalClipboard: true
  )

  public static let conservative = PrivacyPolicy(
    ignoredPasteboardTypes: standard.ignoredPasteboardTypes,
    ignoredTransientTypes: standard.ignoredTransientTypes,
    ignoredAppBundleIds: [
      "com.1password.1password",
      "com.agilebits.onepassword7",
      "com.apple.Terminal",
      "com.googlecode.iterm2"
    ],
    recordsUniversalClipboard: false
  )

  public func shouldIgnore(pasteboardTypes: Set<String>, sourceBundleId: String?) -> Bool {
    if pasteboardTypes.contains("com.apple.is-remote-clipboard") && !recordsUniversalClipboard {
      return true
    }

    if let sourceBundleId, ignoredAppBundleIds.contains(sourceBundleId) {
      return true
    }

    if !pasteboardTypes.isDisjoint(with: ignoredPasteboardTypes) {
      return true
    }

    let nonTransientTypes = pasteboardTypes.subtracting(ignoredTransientTypes)
    if !pasteboardTypes.isDisjoint(with: ignoredTransientTypes), nonTransientTypes.isEmpty {
      return true
    }

    return false
  }
}
